apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cat"
  labels:
    app: cat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
        - name: cat
          image: "gcr.io/gcp-formation-b5uc/cat:v1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 15
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi   
---
apiVersion: v1
kind: Service
metadata:
  name: cat
  labels:
    app: cat
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cat
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cat-ingress
  namespace: default
  annotations:
    flux.weave.works/ignore: 'false'
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.global-static-ip-name: "cat-ingress"
spec:
  backend:
    serviceName: cat
    servicePort: 80
  rules:
  - host: cat.34.98.95.58.xip.io
    http:
      paths:
      - backend:
          serviceName: cat
          servicePort: 80
        path: /
---
